name:                opinion-bot
version:             0.1.0.0
github:              "ryndubei/opinion-bot"
license:             BSD3
author:              "ryndubei"
maintainer:          "114586905+ryndubei@users.noreply.github.com"
copyright:           "2023 ryndubei"

data-files:
- .secrets/*.secret
- negative-words.txt
- positive-words.txt

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ryndubei/opinion-bot#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -haddock

library:
  source-dirs: src

executables:
  opinion-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opinion-bot
    - discord-haskell
    - aeson
    - directory
    - bytestring

tests:
  opinion-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opinion-bot
    - hspec
    - QuickCheck
    - HUnit
